"""tickets client_guid unique

Revision ID: 42112c8726af
Revises: cf0c4297ef3c
Create Date: 2026-02-21 21:03:53.747443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42112c8726af'
down_revision: Union[str, Sequence[str], None] = 'cf0c4297ef3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'client_guid',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'tickets', ['client_guid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='unique')
    op.alter_column('tickets', 'client_guid',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
