"""init schema

Revision ID: cf0c4297ef3c
Revises: 
Create Date: 2026-02-21 16:36:09.387853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf0c4297ef3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('office_name')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_guid', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('house', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tickets_city', 'tickets', ['city'], unique=False)
    op.create_index('ix_tickets_segment', 'tickets', ['segment'], unique=False)
    op.create_table('managers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('business_unit_id', sa.UUID(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_managers_bu_id', 'managers', ['business_unit_id'], unique=False)
    op.create_table('ticket_ai',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('type_category', sa.String(length=64), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lon', sa.Float(), nullable=True),
    sa.Column('confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_index('ix_assignments_business_unit_id', 'assignments', ['business_unit_id'], unique=False)
    op.create_index('ix_assignments_manager_id', 'assignments', ['manager_id'], unique=False)
    op.create_table('rr_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bucket_key', sa.String(length=255), nullable=False),
    sa.Column('last_manager_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_manager_id'], ['managers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_key'),
    sa.UniqueConstraint('bucket_key', name='uq_rr_state_bucket_key')
    )
    op.create_index('ix_rr_state_bucket_key', 'rr_state', ['bucket_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rr_state_bucket_key', table_name='rr_state')
    op.drop_table('rr_state')
    op.drop_index('ix_assignments_manager_id', table_name='assignments')
    op.drop_index('ix_assignments_business_unit_id', table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('ticket_ai')
    op.drop_index('ix_managers_bu_id', table_name='managers')
    op.drop_table('managers')
    op.drop_index('ix_tickets_segment', table_name='tickets')
    op.drop_index('ix_tickets_city', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('business_units')
    # ### end Alembic commands ###
